# Generated by Django 2.2.3 on 2019-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('제목1', '제목1 레이블'), ('제목2', '제목2 레이블'), ('제목3', '제목3 레이블')], max_length=100),
        ),
    ]
